apiVersion: v1
kind: Secret
metadata:
  name: negosuite-api-secret
type: Opaque
data:
  ConnectionString__negosuite: c2VydmVyPXByaXZhdGUtZGItbXlzcWwtbmVnb3N1aXRlLWRvLXVzZXItMTM4MzY4NTgtMC5iLmRiLm9uZGlnaXRhbG9jZWFuLmNvbTtwb3J0PTI1MDYwO3VzZXI9bmVnb3N1aXRlO3Bhc3N3b3JkPWR0c25lZ29zdWl0ZXBmMjAyMztkYXRhYmFzZT1uZWdvc3VpdGVkYjsgQ29udmVydCBaZXJvIERhdGV0aW1lPVRydWU=
stringData:
  Jwt__Key: "Z76ztXf1zpklOp0VI8JlIqRKfU8JQqfp"
  Jwt__Issuer: "https://api.negosuite.com/"
  Jwt__Audience: "https://app.negosuite.com/"
  AppUrl: "https://app.negosuite.com/"
