using System.Linq;
using negosuite_api.Models;
namespace negosuite_api.Contracts.Transactions;

internal static partial class TransactionWriteMapping
{
    public static JournalEntry Map(GeneralJournalJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        GeneralJournalId = value.GeneralJournalId,
        PaymentToJournalEntryId = value.PaymentToJournalEntryId,
    };
    public static GeneralJournal Map(GeneralJournalWriteRequest value) => value == null ? null : new GeneralJournal
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
    };
    public static JournalEntry Map(ReceivingReportJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
    };
    public static ReceivingReport Map(ReceivingReportWriteRequest value) => value == null ? null : new ReceivingReport
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        SupplierId = value.SupplierId,
        LandedCostsJson = value.LandedCostsJson,
        CreditAccountId = value.CreditAccountId,
        PurchaseOrderNo = value.PurchaseOrderNo,
        DeliveryReceiptNo = value.DeliveryReceiptNo,
        Notes = value.Notes,
        Status = value.Status,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        Balance = value.Balance,
        Taxes = value.Taxes,
        IsTaxExclusive = value.IsTaxExclusive,
        DiscountIsBeforeTax = value.DiscountIsBeforeTax,
        HasItemLevelDiscount = value.HasItemLevelDiscount,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        InventoryLocationId = value.InventoryLocationId,
        ReceivingReportDetails = value.ReceivingReportDetails?.Select(Map).ToList(),
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
    };
    public static ReceivingReportDetail Map(ReceivingReportLineRequest value) => value == null ? null : new ReceivingReportDetail
    {
        Id = value.Id,
        ReceivingReportId = value.ReceivingReportId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Rate = value.Rate,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        TaxRateId = value.TaxRateId,
        TaxAmount = value.TaxAmount,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        InventoryLocationId = value.InventoryLocationId,
        LandedCostJson = value.LandedCostJson,
        LandedCost = value.LandedCost,
        Deleted = value.Deleted,
    };
    public static JournalEntry Map(StockIssuanceJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
    };
    public static StockIssuance Map(StockIssuanceWriteRequest value) => value == null ? null : new StockIssuance
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        InventoryLocationId = value.InventoryLocationId,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        StockIssuanceDetails = value.StockIssuanceDetails?.Select(Map).ToList(),
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
    };
    public static StockIssuanceDetail Map(StockIssuanceLineRequest value) => value == null ? null : new StockIssuanceDetail
    {
        Id = value.Id,
        StockIssuanceId = value.StockIssuanceId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Cost = value.Cost,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
    };
    public static StockTransfer Map(StockTransferWriteRequest value) => value == null ? null : new StockTransfer
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        FromInventoryLocationId = value.FromInventoryLocationId,
        ToInventoryLocationId = value.ToInventoryLocationId,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        StockTransferDetails = value.StockTransferDetails?.Select(Map).ToList(),
    };
    public static StockTransferDetail Map(StockTransferLineRequest value) => value == null ? null : new StockTransferDetail
    {
        Id = value.Id,
        StockTransferId = value.StockTransferId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
    };
    public static JournalEntry Map(InventoryAdjustmentJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        InventoryAdjustmentId = value.InventoryAdjustmentId,
    };
    public static InventoryAdjustment Map(InventoryAdjustmentWriteRequest value) => value == null ? null : new InventoryAdjustment
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        InventoryLocationId = value.InventoryLocationId,
        AdjustmentAccountId = value.AdjustmentAccountId,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        InventoryAdjustmentDetails = value.InventoryAdjustmentDetails?.Select(Map).ToList(),
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
    };
    public static InventoryAdjustmentDetail Map(InventoryAdjustmentLineRequest value) => value == null ? null : new InventoryAdjustmentDetail
    {
        Id = value.Id,
        InventoryAdjustmentId = value.InventoryAdjustmentId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Rate = value.Rate,
        Amount = value.Amount,
        Notes = value.Notes,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
    };
    public static JournalEntry Map(SalesInvoiceJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        SalesInvoiceId = value.SalesInvoiceId,
    };
    public static SalesInvoice Map(SalesInvoiceWriteRequest value) => value == null ? null : new SalesInvoice
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        InvoiceNo = value.InvoiceNo,
        InvoiceDate = value.InvoiceDate,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        BillingAddress = value.BillingAddress,
        BillingContactName = value.BillingContactName,
        BillingContactEmail = value.BillingContactEmail,
        ShippingAddress = value.ShippingAddress,
        ShippingContactName = value.ShippingContactName,
        ShippingContactEmail = value.ShippingContactEmail,
        PaymentTermId = value.PaymentTermId,
        DueDate = value.DueDate,
        Notes = value.Notes,
        TermsConditions = value.TermsConditions,
        Status = value.Status,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        Balance = value.Balance,
        Taxes = value.Taxes,
        IsTaxExclusive = value.IsTaxExclusive,
        DiscountIsBeforeTax = value.DiscountIsBeforeTax,
        HasItemLevelDiscount = value.HasItemLevelDiscount,
        PurchaseOrderNo = value.PurchaseOrderNo,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        SalesInvoiceDetails = value.SalesInvoiceDetails?.Select(Map).ToList(),
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        InventoryLocationId = value.InventoryLocationId,
        AutoReferenceNo = value.AutoReferenceNo,
    };
    public static SalesInvoiceDetail Map(SalesInvoiceLineRequest value) => value == null ? null : new SalesInvoiceDetail
    {
        Id = value.Id,
        SalesInvoiceId = value.SalesInvoiceId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Cost = value.Cost,
        Rate = value.Rate,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        TaxRateId = value.TaxRateId,
        TaxAmount = value.TaxAmount,
        TaxExemptAmount = value.TaxExemptAmount,
        Notes = value.Notes,
        IsInventoryTransaction = value.IsInventoryTransaction,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        InventoryLocationId = value.InventoryLocationId,
    };
    public static JournalEntry Map(SalesReceiptJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        SalesReceiptId = value.SalesReceiptId,
    };
    public static SalesReceipt Map(SalesReceiptWriteRequest value) => value == null ? null : new SalesReceipt
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReceiptNo = value.ReceiptNo,
        ReceiptDate = value.ReceiptDate,
        CustomerId = value.CustomerId,
        BillingAddress = value.BillingAddress,
        BillingContactName = value.BillingContactName,
        BillingContactEmail = value.BillingContactEmail,
        ShippingAddress = value.ShippingAddress,
        ShippingContactName = value.ShippingContactName,
        ShippingContactEmail = value.ShippingContactEmail,
        PaymentModeId = value.PaymentModeId,
        DepositToAccountId = value.DepositToAccountId,
        Notes = value.Notes,
        Status = value.Status,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        Balance = value.Balance,
        Taxes = value.Taxes,
        IsTaxExclusive = value.IsTaxExclusive,
        DiscountIsBeforeTax = value.DiscountIsBeforeTax,
        HasItemLevelDiscount = value.HasItemLevelDiscount,
        PurchaseOrderNo = value.PurchaseOrderNo,
        PostedDate = value.PostedDate,
        IsPOS = value.IsPOS,
        PaymentDetails = value.PaymentDetails,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        SalesReceiptDetails = value.SalesReceiptDetails?.Select(Map).ToList(),
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        InventoryLocationId = value.InventoryLocationId,
        AutoReferenceNo = value.AutoReferenceNo,
    };
    public static SalesReceiptDetail Map(SalesReceiptLineRequest value) => value == null ? null : new SalesReceiptDetail
    {
        Id = value.Id,
        SalesReceiptId = value.SalesReceiptId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Cost = value.Cost,
        Rate = value.Rate,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        TaxRateId = value.TaxRateId,
        TaxAmount = value.TaxAmount,
        TaxExemptAmount = value.TaxExemptAmount,
        Notes = value.Notes,
        IsInventoryTransaction = value.IsInventoryTransaction,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        InventoryLocationId = value.InventoryLocationId,
    };
    public static JournalEntry Map(SalesInvoicePaymentJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        SalesInvoicePaymentId = value.SalesInvoicePaymentId,
        PaymentToJournalEntryId = value.PaymentToJournalEntryId,
    };
    public static SalesInvoicePayment Map(SalesInvoicePaymentWriteRequest value) => value == null ? null : new SalesInvoicePayment
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        CustomerId = value.CustomerId,
        PaymentModeId = value.PaymentModeId,
        DepositToAccountId = value.DepositToAccountId,
        Notes = value.Notes,
        Status = value.Status,
        Amount = value.Amount,
        Balance = value.Balance,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
    };
}
