using System.Linq;
using negosuite_api.Contracts.Bills;
using negosuite_api.Contracts.Payments;
using negosuite_api.Models;

namespace negosuite_api.Contracts.Transactions;

// Navigation objects from legacy clients are ignored by request binding.
internal static partial class TransactionWriteMapping
{
    public static Bill Map(BillWriteRequest value) => value == null ? null : new Bill
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        BillNo = value.BillNo,
        BillDate = value.BillDate,
        SupplierId = value.SupplierId,
        PaymentTermId = value.PaymentTermId,
        DueDate = value.DueDate,
        Notes = value.Notes,
        Status = value.Status,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        Balance = value.Balance,
        Taxes = value.Taxes,
        IsTaxExclusive = value.IsTaxExclusive,
        DiscountIsBeforeTax = value.DiscountIsBeforeTax,
        HasItemLevelDiscount = value.HasItemLevelDiscount,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        InventoryLocationId = value.InventoryLocationId,
        BillDetails = value.BillDetails?.Select(Map).ToList(),
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
    };
    public static Payment Map(PaymentWriteRequest value) => value == null ? null : new Payment
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        ReferenceDate = value.ReferenceDate,
        SupplierId = value.SupplierId,
        CustomerId = value.CustomerId,
        IsBillPayment = value.IsBillPayment,
        Payee = value.Payee,
        PaymentModeId = value.PaymentModeId,
        CheckNo = value.CheckNo,
        PaidThroughAccountId = value.PaidThroughAccountId,
        Notes = value.Notes,
        Status = value.Status,
        Amount = value.Amount,
        Balance = value.Balance,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        JournalEntries = value.JournalEntries?.Select(Map).ToList(),
    };
    public static BillDetail Map(BillLineRequest value) => value == null ? null : new BillDetail
    {
        Id = value.Id,
        BillId = value.BillId,
        ItemId = value.ItemId,
        Quantity = value.Quantity,
        Rate = value.Rate,
        DiscountAmount = value.DiscountAmount,
        DiscountPercent = value.DiscountPercent,
        Amount = value.Amount,
        TaxRateId = value.TaxRateId,
        TaxAmount = value.TaxAmount,
        Notes = value.Notes,
        IsInventoryTransaction = value.IsInventoryTransaction,
        Status = value.Status,
        PostedDate = value.PostedDate,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        InventoryLocationId = value.InventoryLocationId,
        LandedCostJson = value.LandedCostJson,
        LandedCost = value.LandedCost,
        Deleted = value.Deleted,
        Touched = value.Touched,
    };
    public static JournalEntry Map(BillJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        BillId = value.BillId,
    };
    public static JournalEntry Map(PaymentJournalRequest value) => value == null ? null : new JournalEntry
    {
        Id = value.Id,
        UserConfigId = value.UserConfigId,
        ReferenceNo = value.ReferenceNo,
        JournalDate = value.JournalDate,
        AccountId = value.AccountId,
        Amount = value.Amount,
        Balance = value.Balance,
        Nature = value.Nature,
        ResponsibilityCenterEntry = value.ResponsibilityCenterEntry,
        CustomerId = value.CustomerId,
        SupplierId = value.SupplierId,
        DebtorId = value.DebtorId,
        CreditorId = value.CreditorId,
        Notes = value.Notes,
        Source = value.Source,
        CurrencyXrate = value.CurrencyXrate,
        Status = value.Status,
        PostedDate = value.PostedDate,
        PostedByUserId = value.PostedByUserId,
        DueDate = value.DueDate,
        TaxRateId = value.TaxRateId,
        IsComputed = value.IsComputed,
        Particular = value.Particular,
        Payee = value.Payee,
        Payor = value.Payor,
        PaymentAdjustmentEntry = value.PaymentAdjustmentEntry,
        CreatedDate = value.CreatedDate,
        LastUpdatedDate = value.LastUpdatedDate,
        CreatedByUserId = value.CreatedByUserId,
        LastUpdatedByUserId = value.LastUpdatedByUserId,
        Deleted = value.Deleted,
        PaymentId = value.PaymentId,
        PaymentToJournalEntryId = value.PaymentToJournalEntryId,
    };
}
